### ISSUE TITLE
Error accessing uninitialized property

### ISSUE THREAD

**Issue by javiereguiluz** [symfonycorp/connect#126]
I finally could update a big Symfony app to 7.0. When trying to browse the app, I see this error:

```
Typed property Symfony\Component\HttpKernel\Bundle\Bundle::$extension
must not be accessed before initialization
```

The error happens here:
https://github.com/symfonycorp/connect/blob/ef075c748c87d1198b77f354395f3442df70624d/src/SymfonyConnectBundle.php#L30

@nicolas-grekas did you expect this issue? What would be the best way to solve this? Thanks!

**Comment by alexandre-daubois** [comment]
I guess this can be closed as fixed by https://github.com/symfony/symfony/pull/52438 :slightly_smiling_face:
