### ISSUE TITLE
Issues with serialization / deserialization of the token (and injected-objects)

### ISSUE THREAD

**Issue by csarrazi** [symfonycorp/connect#15]
There are a few issues with serialization / deserialization.
When serializing the token, everything is stored in the session storage. When restoring the session, there are a few issues, especially with external classes (such as the logger, in the case you use a Monolog stream handler, which doesn't have any protection against deserialization).

This issue is pretty simple to test.

Inside any Symfony2 controller of an application using ConnectBundle (apart from the interactive login), the following code should fail, monolog complaining about not being able to open the resource in case you set it up with a stream handler.

``` php
$user = $this->get('security.context')->getToken()->getApiUser()->refresh();
```

**Comment by nicolas-grekas** [comment]
Closing as this is more a Symfony thing AFAIK, and discussion is happening on the topic already there.
