### ISSUE TITLE
Couldn't load image url with getBadge() method

### ISSUE THREAD

**Issue by inalgnu** [symfonycorp/connect#38]
The following method set the link to badge's image

``` php
protected function getLinkToFoafDepiction(\DOMElement $element)
{
        return $this->getLinkNodeHref('./atom:link[@rel="foaf:depiction"]', $element);
}
```

however there is no reference to **foaf:depiction** in fixtures https://github.com/sensiolabs/connect/tree/master/tests/fixtures.

The badges images are always set to null.

Should this to be fixed on the SDK side?

ping @marcw @lyrixx

**Comment by lyrixx** [comment]
@inalgnu Could we close this issue?
