### ISSUE TITLE
The SensioLabs Connect connection should redirect to the current page

### ISSUE THREAD

**Issue by stof** [symfonycorp/connect#43]
This issue is related to the connect website and its integration in other Symfony/SensioLabs website, but there is no public issue tracker for it AFAIK, so I'm opening it on the SDK repo.

It is very annoying that each time you connect with SensioLabsConnect, you get redirected to the homepage of the website instead of staying on the current page. The redirection should go to the page where we were before the connection.
- [x] connect
- [X] insight
- [x] live
- [x] symfony
- [x] sensiolabs
- [ ] trainings
- [ ] profiler

**Comment by lyrixx** [comment]
I think this issue can be closed?

**Comment by javiereguiluz** [comment]
Yes, let's close it. Thanks!
