### ISSUE TITLE
Not getting all information of the user

### ISSUE THREAD

**Issue by saro0h** [symfonycorp/connect#58]
I need the user's picture but I'm getting nothing from Connect:

```
properties: array:23 [▼
    "username" => "saro0h"
    "uuid" => "…"
    "name" => "Sarah Khalil"
    "image" => null
    …
```

The scope of my app is `SCOPE_PUBLIC`, I should access it right?

**Comment by lyrixx** [comment]
I don't know.
Is this field present in the XML?
Could you open a PR in the connect repository to fix this issue if it not in the XML?
