### ISSUE TITLE
[BUG] Facebook app :)

### ISSUE THREAD

**Issue by Warxcell** [symfonycorp/connect#65]
I went to official https://connect.sensiolabs.com/

Profile => Your online Profile => Facebook => Link your facebook account

and this is what I got 

![image](https://user-images.githubusercontent.com/3340882/45515432-d4602d00-b7b0-11e8-9d7e-9578695a63fe.png)

:)

**Comment by azjezz** [comment]
Facebook integration has been removed as of today.
