### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by arcristo** [symfonycorp/connect#66]
The certificate for connect.sensiolabs.com expired on Dec 28th.

**Comment by lyrixx** [comment]
@arcristo It's connect.symfony.com now.

**Comment by arcristo** [comment]
Thanks, @lyrixx. I was gathering some more context info.

The error occurs when I try to follow the steps to purchase a voucher at https://certification.symfony.com.

Indeed, the request was made to https://connect.sensiolabs.com/oauth/authorize.

Any other place where I can report this bug?

**Comment by javiereguiluz** [comment]
@arcristo we're on it at this very moment. I'll update progress here. Thanks!

**Comment by javiereguiluz** [comment]
@arcristo we've deployed some fixes that solved the problem when testing it locally. Could you please test it and tell us if it worked? Thanks!

**Comment by arcristo** [comment]
@javiereguiluz thanks, the form is working now.

About the Connect button:

- I first time I click on Connect button the login page appears and I can proceed to login.
- If I click on Logout from https://certification.symfony.com/manager/profile and try to log in
again, I am automatically logged in.
- If I log out from https://connect.symfony.com but not from https://certification.symfony.com my session on the last one is maintained.
- Only after log out from https://connect.symfony.com and then from https://certification.symfony.com the log in page appears again, on a new attempt of log in. Is this intended?

If so, everything is OK. Thanks!

**Comment by javiereguiluz** [comment]
@arcristo thanks for checking this! Yes, that behaviour is expected for certification.symfony.com because it's the same we already apply on symfony.com and other Symfony websites.

So, I'm closing this issue as "fixed". Thanks!
